/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseNav: typeof import('./components/BaseNav.vue')['default']
    Contact: typeof import('./components/Contact.vue')['default']
    EventModal: typeof import('./components/EventModal.vue')['default']
    EventsList: typeof import('./components/EventsList.vue')['default']
    FairgroundsNav: typeof import('./components/FairgroundsNav.vue')['default']
    FairNav: typeof import('./components/FairNav.vue')['default']
    FavoriteButton: typeof import('./components/FavoriteButton.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialIcons: typeof import('./components/SocialIcons.vue')['default']
  }
}
