/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseNav: typeof import('./components/BaseNav.vue')['default']
    BaseTabNavigation: typeof import('./components/tabs/BaseTabNavigation.vue')['default']
    CalendarIcon: typeof import('./components/icons/CalendarIcon.vue')['default']
    Contact: typeof import('./components/Contact.vue')['default']
    EventCarousel: typeof import('./components/EventCarousel.vue')['default']
    EventModal: typeof import('./components/EventModal.vue')['default']
    EventsList: typeof import('./components/EventsList.vue')['default']
    FairBottomNavigation: typeof import('./components/tabs/FairBottomNavigation.vue')['default']
    FairgroundsBottomNavigation: typeof import('./components/tabs/FairgroundsBottomNavigation.vue')['default']
    FairgroundsMenu: typeof import('./components/icons/FairgroundsMenu.vue')['default']
    FairgroundsNav: typeof import('./components/FairgroundsNav.vue')['default']
    FairNav: typeof import('./components/FairNav.vue')['default']
    FavoriteButton: typeof import('./components/FavoriteButton.vue')['default']
    FGKeepInTouch: typeof import('./components/FGKeepInTouch.vue')['default']
    FloatingNav: typeof import('./components/FloatingNav.vue')['default']
    HamburgerIcon: typeof import('./components/icons/HamburgerIcon.vue')['default']
    HomeIcon: typeof import('./components/icons/HomeIcon.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    MapDetailsPopup: typeof import('./components/MapDetailsPopup.vue')['default']
    MapIcon: typeof import('./components/icons/MapIcon.vue')['default']
    PinIcon: typeof import('./components/icons/PinIcon.vue')['default']
    PlaceholderIcon: typeof import('./components/icons/PlaceholderIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleIcon: typeof import('./components/icons/ScheduleIcon.vue')['default']
    SocialIcons: typeof import('./components/SocialIcons.vue')['default']
    StartIcon: typeof import('./components/icons/StartIcon.vue')['default']
    TicketsIcon: typeof import('./components/icons/TicketsIcon.vue')['default']
  }
}
